"""``Setup.md``: everything this run configured, written out as one readable document.

The point of the file is that it is complete: the endpoints, every setting the operator chose,
every path on the server, and **the credentials in clear text** - the database and Redis
passwords, the JWT signing key, the intelligence shared secret, the server's AWS access key and
the SMTP password. Nothing here is redacted, because a copy of the passwords that masks them is
worth nothing at three in the morning.

That is also why :func:`write_setup_markdown` creates the file ``0600`` and why the GUI asks
before writing one: the document is as sensitive as the server itself.
"""

from __future__ import annotations

import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from cloud_driver_installer.config_files import SCREEN_LOG_FILE
from cloud_driver_installer.model import Discovered, GeneratedSecrets, InstallPlan
from cloud_driver_installer.sizing import format_bytes

#: The line every export carries at the top, so nobody mistakes it for a redacted report.
SECRET_WARNING = (
    "> **This file contains every password and key of this deployment in clear text.** "
    "Keep it in a password manager or an encrypted volume, never in the repository, "
    "a ticket, a chat message or a backup that others can read."
)

#: What is written where a value has not been set (or has not been read back from the server).
UNSET = "_not set_"


class Note(str):
    """A cell that is an explanation, not a value: rendered as prose, never code-quoted."""


def _value(value: Any) -> str:
    """Render one cell: booleans as yes/no, empty as :data:`UNSET`, :class:`Note` as prose.

    Everything else is code-quoted, because a host, a port, a path, a command or a password is
    something the reader copies, and markdown would otherwise eat the underscores in a key.
    """
    if isinstance(value, Note):
        return str(value)
    if isinstance(value, bool):
        return "yes" if value else "no"
    if value is None or value == "":
        return UNSET
    return f"`{value}`"


def _table(rows: list[tuple[str, Any]]) -> list[str]:
    """A two-column markdown table, empty rows dropped."""
    lines = ["| Setting | Value |", "| --- | --- |"]
    lines += [f"| {name} | {_value(value)} |" for name, value in rows]
    return lines


def _section(title: str, rows: list[tuple[str, Any]]) -> list[str]:
    """One ``## title`` plus its table, with the blank lines markdown needs around a table."""
    return [f"## {title}", "", *_table(rows), ""]


def render_setup_markdown(
    plan: InstallPlan,
    secrets: GeneratedSecrets,
    discovered: Discovered | None = None,
    *,
    generated_at: datetime | None = None,
) -> str:
    """Return the complete ``Setup.md`` for this plan, secrets included.

    ``discovered`` is optional: an export made before the first check simply has no facts about
    the server yet, and says so rather than inventing them.
    """
    found = discovered or Discovered()
    when = (generated_at or datetime.now(timezone.utc)).strftime("%Y-%m-%d %H:%M UTC")
    public = plan.public_api_url(found.public_ip)
    install_dir = plan.server.install_dir.rstrip("/")

    lines: list[str] = [
        "# cloud-driver deployment",
        "",
        f"Generated by cloud-driver-installer on {when} for **{plan.ssh.label()}**.",
        "",
        SECRET_WARNING,
        "",
        "## At a glance",
        "",
        *_table([
            ("API endpoint", public or Note("not reachable from outside - see Reverse proxy")),
            ("Server", f"{plan.ssh.user}@{plan.ssh.host}:{plan.ssh.port}"),
            ("Operating system", found.os_pretty),
            ("Public address", found.public_ip),
            ("Install directory", install_dir),
            ("Operator terminal", f"screen -r {plan.server.screen_session}"),
            ("Console log", SCREEN_LOG_FILE),
        ]),
        "",
    ]

    lines += _section("Credentials", [
        ("PostgreSQL password", secrets.pg_password),
        ("Redis password", secrets.redis_password),
        ("JWT signing key", secrets.jwt_signing_key),
        ("Intelligence shared secret", secrets.intelligence_secret),
        ("AWS access key id (on the server)", secrets.server_access_key_id),
        ("AWS secret access key", secrets.server_secret_access_key or Note("not held by this run - only a key created in this run is shown")),
        ("SMTP password", plan.email.smtp_password if plan.email.mode == "smtp" else ""),
    ])

    lines += _section("Server", [
        ("Install directory", install_dir),
        ("Configuration directory", plan.config_dir),
        ("Extensions directory", plan.extensions_dir),
        ("screen session", plan.server.screen_session),
        ("Timezone", plan.server.timezone or Note("kept as the host had it")),
        ("Unattended security upgrades", plan.server.unattended_upgrades),
        ("Firewall (ufw)", plan.server.firewall),
        ("Extra firewall ports", plan.server.firewall_extra_ports),
        ("Swap", f"{plan.server.swap_mb} MB" if plan.server.swap_mb else Note("none")),
        ("SSH alias", plan.server.ssh_alias_name if plan.server.write_ssh_alias else ""),
        ("RAM", f"{found.ram_mib / 1024:.1f} GiB" if found.ram_mib else ""),
        ("Free disk", f"{found.disk_free_gib:.0f} GiB" if found.disk_free_gib else ""),
        ("Java", found.java_version),
        ("Python", found.python_version),
    ])

    pg = plan.postgres
    lines += _section("PostgreSQL", [
        ("Mode", Note("installed on this server" if pg.mode == "install" else "external server")),
        ("Host", pg.host),
        ("Port", pg.port),
        ("Database", pg.database),
        ("User", pg.username),
        ("Password", secrets.pg_password),
        ("Credentials file", f"{plan.config_dir}/postgres-database.json"),
        ("Version", found.pg_version),
    ])

    redis = plan.redis
    lines += _section("Redis", [
        ("Enabled", redis.enabled),
        ("Mode", Note("installed on this server" if redis.mode == "install" else "external server")),
        ("Host", redis.host),
        ("Port", redis.port),
        ("Database index", redis.database),
        ("Password", secrets.redis_password),
        ("Credentials file", f"{plan.config_dir}/redis-database.json"),
    ] if redis.enabled else [("Enabled", False)])

    aws = plan.aws
    lines += _section("AWS", [
        ("Region", aws.region),
        ("KMS key", secrets.kms_key_id or (aws.kms_key_id if aws.kms_mode == "existing" else aws.kms_alias)),
        ("KMS key ARN", secrets.kms_key_arn),
        ("S3 content bucket", aws.s3_bucket if aws.s3_enabled else Note("S3 disabled - content is stored inline in Postgres")),
        ("S3 key prefix", aws.s3_key_prefix),
        ("Off-site backup bucket", aws.effective_backup_bucket if plan.app.backup_offsite else ""),
        ("Backup retention", f"{aws.backup_retention_days} days" if plan.app.backup_offsite else ""),
        ("Server identity", aws.iam_user_name if aws.server_identity == "iam_user" else Note("the operator's own credentials")),
        ("Access key id", secrets.server_access_key_id),
        ("Secret access key", secrets.server_secret_access_key or Note("not held by this run")),
        ("Credentials file", "/root/.aws/credentials"),
    ])

    email = plan.email
    if email.mode == "ses":
        rows: list[tuple[str, Any]] = [
            ("Transport", Note("Amazon SES")),
            ("Region", plan.ses_region),
            ("From address", email.ses_from_address),
            ("Identity", Note("domain (Easy DKIM)" if email.ses_identity_mode == "domain" else "single address")),
            ("Configuration set", email.ses_configuration_set),
        ]
    elif email.mode == "smtp":
        rows = [
            ("Transport", Note("SMTP relay")),
            ("Host", email.smtp_host),
            ("Port", email.smtp_port),
            ("Username", email.smtp_username),
            ("Password", email.smtp_password),
            ("From address", email.smtp_from_address),
        ]
    else:
        rows = [("Transport", Note("none - verification codes only appear in the server log"))]
    lines += _section("E-mail", rows)
    if secrets.ses_dkim_records:
        lines += ["The DKIM records to publish:", "", "| Name | Type | Value |", "| --- | --- | --- |"]
        lines += [f"| `{name}` | CNAME | `{value}` |" for name, value in secrets.ses_dkim_records]
        lines += [""]

    lines += _section("Reverse proxy", [
        ("Enabled", plan.proxy.enabled),
        ("API domain", plan.proxy.api_domain or Note("none - Caddy serves plain HTTP on port 80 for this server's address")),
        ("ACME e-mail", plan.proxy.acme_email),
        ("Upstream", f"127.0.0.1:{plan.app.rest_port}"),
        ("Public URL", public or Note("not reachable from outside")),
    ])

    app = plan.app
    lines += _section("Application", [
        ("REST listener", f"{app.rest_bind_host}:{app.rest_port}"),
        ("Metrics listener", f"{app.metrics_bind_host}:{app.metrics_port}"),
        ("Server capacity", format_bytes(app.server_max_bytes)),
        ("Per-user quota", format_bytes(app.user_max_bytes)),
        ("JVM heap", app.jvm_xmx or Note("sized from the server's RAM")),
        ("Start after deploy", app.start_after_deploy),
        ("Autostart on reboot", app.autostart_on_reboot),
        ("Off-site database backup", app.backup_offsite),
        ("JWT signing key", secrets.jwt_signing_key),
        ("Launcher", f"{install_dir}/start-cloud.sh"),
    ])

    lines += _section("Malware scanning (ClamAV)", [
        ("Enabled", plan.clamav.enabled),
        ("Endpoint", f"{plan.clamav.host}:{plan.clamav.port}" if plan.clamav.enabled else ""),
        ("Max scanned size", format_bytes(plan.clamav.content_scan_max_bytes) if plan.clamav.enabled else ""),
    ])

    intelligence = plan.intelligence
    lines += _section("Intelligence service", [
        ("Enabled", intelligence.enabled),
        ("Endpoint", f"127.0.0.1:{intelligence.port}" if intelligence.enabled else ""),
        ("Shared secret", secrets.intelligence_secret),
        ("At-rest encryption", intelligence.enable_encryption if intelligence.enabled else ""),
        ("OCR", f"{intelligence.ocr_languages}" if intelligence.enabled and intelligence.ocr else ("no" if intelligence.enabled else "")),
        ("Install directory", "/opt/cloud-driver-intelligence" if intelligence.enabled else ""),
    ])

    lines += [
        "## Running it",
        "",
        f"- Attach to the operator terminal: `ssh {plan.ssh.user}@{plan.ssh.host} -p {plan.ssh.port}` then `screen -r {plan.server.screen_session}` (detach again with Ctrl-A d).",
        f"- Start or restart the backend: `cd {install_dir} && ./start-cloud.sh`.",
        "- Make the first registered account an administrator: `admin grant <e-mail>` in that terminal.",
        f"- Configuration the JVM reads at boot: `{plan.config_dir}/configuration.json` (plus the two credentials files).",
        "",
    ]
    warnings = plan.warnings(discovered)
    if warnings:
        lines += ["## Worth knowing", "", *[f"- {note}" for note in warnings], ""]
    return "\n".join(lines).rstrip("\n") + "\n"


def write_setup_markdown(
    path: str | Path,
    plan: InstallPlan,
    secrets: GeneratedSecrets,
    discovered: Discovered | None = None,
) -> Path:
    """Write :func:`render_setup_markdown` to ``path`` with ``0600`` permissions; returns the path."""
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_setup_markdown(plan, secrets, discovered), encoding="utf-8")
    os.chmod(target, 0o600)
    return target
