<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>de.lino.cloud</groupId>
        <artifactId>cloud-driver</artifactId>
        <version>1.0.1</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <groupId>de.lino.cloud.extensions</groupId>
    <artifactId>cloud-driver-extensions</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>cloud-driver-extensions-rest</module>
        <module>cloud-driver-extensions-watcher</module>
        <module>cloud-driver-extension-terminal</module>
    </modules>

</project>