"""Tests for the ClamAV step: the pure clamd.conf / drop-in editors and the check → apply → verify phases."""

from __future__ import annotations

import pytest

from cloud_driver_installer.engine import Context, StepError, StepStatus
from cloud_driver_installer.model import InstallPlan
from cloud_driver_installer.steps.clamav import (
    CLAMD_CONF,
    DROP_IN_DIR,
    DROP_IN_PATH,
    UNITS,
    ClamAvStep,
    apply_clamd_limits,
    clamd_limit_values,
    drop_in_is_current,
    drop_in_listeners,
    listen_address,
    render_drop_in,
    stale_limits,
    wanted_limits,
)

from fake_remote import FakeRemote

DEBIAN_DEFAULT_CONF = (
    "# Automatically Generated by clamav-daemon postinst\n"
    "LocalSocket /var/run/clamav/clamd.ctl\n"
    "StreamMaxLength 25M\n"
    "MaxFileSize 25M\n"
    "MaxScanSize 100M\n"
    "#TCPSocket 3310\n"
    "LogFile /var/log/clamav/clamav.log\n"
)

PROVISIONED_CONF = (
    "LocalSocket /var/run/clamav/clamd.ctl\n"
    "StreamMaxLength 128M\n"
    "MaxFileSize 128M\n"
    "MaxScanSize 300M\n"
)


def _installed(remote: FakeRemote) -> None:
    remote.ok("dpkg-query -W -f='${Status}' clamav-daemon", "install ok installed")
    remote.ok("dpkg-query -W -f='${Status}' clamav-freshclam", "install ok installed")


def _provisioned(remote: FakeRemote) -> None:
    """A box where everything is already in place."""
    _installed(remote)
    remote.files[DROP_IN_PATH] = render_drop_in("127.0.0.1", 3310)
    remote.files[CLAMD_CONF] = PROVISIONED_CONF
    remote.ok("systemctl is-enabled --quiet")
    remote.ok("systemctl is-active --quiet clamav-daemon.socket")
    remote.ok("systemctl is-active --quiet clamav-freshclam")


def _fast(step: ClamAvStep) -> ClamAvStep:
    step.poll_timeout = 0.0
    step.poll_interval = 0.0
    return step


# --- pure helpers -------------------------------------------------------------------------------------


def test_listen_address_maps_localhost_and_refuses_ipv6() -> None:
    assert listen_address("127.0.0.1") == "127.0.0.1"
    assert listen_address("localhost") == "127.0.0.1"
    assert listen_address("") == "127.0.0.1"
    with pytest.raises(StepError):
        listen_address("::1")


def test_render_drop_in_has_exactly_one_ipv4_listener() -> None:
    text = render_drop_in("127.0.0.1", 3310)
    assert text == "[Socket]\nListenStream=127.0.0.1:3310\n"
    assert drop_in_listeners(text) == ["127.0.0.1:3310"]
    assert drop_in_is_current(text, "127.0.0.1", 3310)
    assert not drop_in_is_current(text, "127.0.0.1", 3311)
    assert not drop_in_is_current(None, "127.0.0.1", 3310)


def test_drop_in_with_a_second_ipv6_listener_is_not_current() -> None:
    text = "[Socket]\nListenStream=127.0.0.1:3310\nListenStream=[::1]:3310\n"
    assert drop_in_listeners(text) == ["127.0.0.1:3310", "[::1]:3310"]
    assert not drop_in_is_current(text, "127.0.0.1", 3310)


def test_clamd_limit_values_ignore_commented_lines() -> None:
    values = clamd_limit_values("StreamMaxLength 25M\n#MaxFileSize 25M\nMaxScanSize\t300M\n")
    assert values == {"StreamMaxLength": "25M", "MaxFileSize": None, "MaxScanSize": "300M"}
    assert clamd_limit_values(None) == {"StreamMaxLength": None, "MaxFileSize": None, "MaxScanSize": None}


def test_apply_clamd_limits_replaces_in_place_and_appends_missing() -> None:
    wanted = wanted_limits(InstallPlan())
    result = apply_clamd_limits(DEBIAN_DEFAULT_CONF, wanted)
    lines = result.splitlines()
    assert lines[2] == "StreamMaxLength 128M"
    assert lines[3] == "MaxFileSize 128M"
    assert lines[4] == "MaxScanSize 300M"
    assert lines[0] == "# Automatically Generated by clamav-daemon postinst"
    assert "#TCPSocket 3310" in lines
    assert result.endswith("\n")
    assert stale_limits(result, wanted) == []
    assert apply_clamd_limits(result, wanted) == result

    appended = apply_clamd_limits("LocalSocket /var/run/clamav/clamd.ctl\n#MaxFileSize 25M\n", wanted)
    assert appended == (
        "LocalSocket /var/run/clamav/clamd.ctl\n#MaxFileSize 25M\n"
        "StreamMaxLength 128M\nMaxFileSize 128M\nMaxScanSize 300M\n"
    )
    assert apply_clamd_limits("", wanted) == "StreamMaxLength 128M\nMaxFileSize 128M\nMaxScanSize 300M\n"


def test_stale_limits_compares_sizes_not_spelling() -> None:
    wanted = wanted_limits(InstallPlan())
    assert stale_limits(DEBIAN_DEFAULT_CONF, wanted) == ["StreamMaxLength", "MaxFileSize", "MaxScanSize"]
    assert stale_limits("StreamMaxLength 131072K\nMaxFileSize 128M\nMaxScanSize 300M\n", wanted) == []
    assert stale_limits(None, wanted) == ["StreamMaxLength", "MaxFileSize", "MaxScanSize"]


# --- check ----------------------------------------------------------------------------------------------


def test_enabled_follows_the_plan(plan: InstallPlan) -> None:
    step = ClamAvStep()
    assert step.enabled(plan)
    plan.clamav.enabled = False
    assert not step.enabled(plan)
    assert step.depends_on == ("packages",)


def test_check_needs_apply_on_bare_box(ctx: Context, remote: FakeRemote) -> None:
    result = ClamAvStep().check(ctx)
    assert result.status is StepStatus.NEEDS_APPLY
    assert "install clamav-daemon, clamav-freshclam" in result.detail
    assert f"write {DROP_IN_PATH} (ListenStream=127.0.0.1:3310)" in result.detail
    assert "StreamMaxLength 128M" in result.detail and CLAMD_CONF in result.detail
    assert "enable clamav-daemon.socket" in result.detail
    assert ctx.discovered.clamd_installed is False
    # read-only: nothing written, nothing installed, no restart
    assert remote.files == {}
    assert remote.apt_installed == []
    assert not remote.ran("systemctl restart")
    assert not remote.ran("systemctl enable")


def test_check_ok_on_provisioned_box(ctx: Context, remote: FakeRemote) -> None:
    _provisioned(remote)
    result = ClamAvStep().check(ctx)
    assert result.status is StepStatus.OK
    assert "127.0.0.1:3310" in result.detail
    assert "StreamMaxLength 128M / MaxFileSize 128M / MaxScanSize 300M" in result.detail
    assert ctx.discovered.clamd_installed is True
    assert remote.backups == []
    assert remote.apt_installed == []


def test_check_flags_dual_listenstream_and_stale_limits(ctx: Context, remote: FakeRemote) -> None:
    _provisioned(remote)
    remote.files[DROP_IN_PATH] = "[Socket]\nListenStream=127.0.0.1:3310\nListenStream=[::1]:3310\n"
    remote.files[CLAMD_CONF] = DEBIAN_DEFAULT_CONF
    result = ClamAvStep().check(ctx)
    assert result.status is StepStatus.NEEDS_APPLY
    assert "replacing 127.0.0.1:3310, [::1]:3310" in result.detail
    assert "set StreamMaxLength 128M, MaxFileSize 128M, MaxScanSize 300M" in result.detail
    assert any(level == "WARN" and "crash-loops" in message for level, message in ctx.captured_log)


def test_check_needs_apply_when_socket_inactive(ctx: Context, remote: FakeRemote) -> None:
    _installed(remote)
    remote.files[DROP_IN_PATH] = render_drop_in("127.0.0.1", 3310)
    remote.files[CLAMD_CONF] = PROVISIONED_CONF
    remote.ok("systemctl is-enabled --quiet")
    result = ClamAvStep().check(ctx)
    assert result.status is StepStatus.NEEDS_APPLY
    assert result.detail == "restart clamav-daemon.socket (not active)"


def test_check_honours_plan_host_and_port(ctx: Context, remote: FakeRemote) -> None:
    ctx.plan.clamav.host = "localhost"
    ctx.plan.clamav.port = 3400
    _provisioned(remote)
    remote.files[DROP_IN_PATH] = render_drop_in("127.0.0.1", 3400)
    assert ClamAvStep().check(ctx).status is StepStatus.OK
    remote.files[DROP_IN_PATH] = render_drop_in("127.0.0.1", 3310)
    result = ClamAvStep().check(ctx)
    assert result.status is StepStatus.NEEDS_APPLY
    assert "ListenStream=127.0.0.1:3400, replacing 127.0.0.1:3310" in result.detail


# --- apply ----------------------------------------------------------------------------------------------


def test_apply_on_bare_box_installs_writes_and_restarts(ctx: Context, remote: FakeRemote) -> None:
    # clamd.conf is what the package's postinst leaves behind; the fake cannot model apt, so seed it.
    remote.files[CLAMD_CONF] = DEBIAN_DEFAULT_CONF
    remote.ok("systemctl daemon-reload")
    remote.ok("systemctl enable")
    ClamAvStep().apply(ctx)

    assert remote.apt_installed == ["clamav-daemon", "clamav-freshclam"]
    assert remote.ran(f"mkdir -p {DROP_IN_DIR}")
    assert remote.files[DROP_IN_PATH] == "[Socket]\nListenStream=127.0.0.1:3310\n"
    assert remote.modes[DROP_IN_PATH] == 0o644
    conf = remote.files[CLAMD_CONF]
    assert "StreamMaxLength 128M\nMaxFileSize 128M\nMaxScanSize 300M\n" in conf
    assert "StreamMaxLength 25M" not in conf
    assert "#TCPSocket 3310" in conf
    assert f"{CLAMD_CONF}.bak-TEST" in remote.backups
    assert remote.files[f"{CLAMD_CONF}.bak-TEST"] == DEBIAN_DEFAULT_CONF
    assert ("daemon-reload",) in remote.systemctl_calls
    assert ("enable", "--quiet", *UNITS) in remote.systemctl_calls
    assert remote.ran("systemctl restart clamav-daemon.socket clamav-daemon clamav-freshclam || true")
    assert ctx.discovered.clamd_installed is True
    # the apt install ran before the drop-in was written
    assert remote.commands.index("apt-get install clamav-daemon clamav-freshclam") < remote.commands.index(f"mkdir -p {DROP_IN_DIR}")


def test_apply_is_idempotent_on_provisioned_box(ctx: Context, remote: FakeRemote) -> None:
    _provisioned(remote)
    remote.ok("systemctl daemon-reload")
    remote.ok("systemctl enable")
    before = dict(remote.files)
    ClamAvStep().apply(ctx)
    assert remote.files == before
    assert remote.backups == []
    assert remote.apt_installed == []
    assert not remote.ran("systemctl restart")
    assert ("enable", "--quiet", *UNITS) in remote.systemctl_calls


def test_apply_restarts_when_only_the_socket_is_inactive(ctx: Context, remote: FakeRemote) -> None:
    _installed(remote)
    remote.files[DROP_IN_PATH] = render_drop_in("127.0.0.1", 3310)
    remote.files[CLAMD_CONF] = PROVISIONED_CONF
    remote.ok("systemctl is-enabled --quiet")
    remote.ok("systemctl daemon-reload")
    remote.ok("systemctl enable")
    ClamAvStep().apply(ctx)
    assert remote.backups == []
    assert remote.ran("systemctl restart clamav-daemon.socket clamav-daemon clamav-freshclam || true")


def test_apply_rewrites_a_dual_listener_drop_in(ctx: Context, remote: FakeRemote) -> None:
    _provisioned(remote)
    remote.files[DROP_IN_PATH] = "[Socket]\nListenStream=127.0.0.1:3310\nListenStream=[::1]:3310\n"
    remote.ok("systemctl daemon-reload")
    remote.ok("systemctl enable")
    ClamAvStep().apply(ctx)
    assert remote.files[DROP_IN_PATH] == "[Socket]\nListenStream=127.0.0.1:3310\n"
    assert f"{DROP_IN_PATH}.bak-TEST" in remote.backups
    assert remote.files[CLAMD_CONF] == PROVISIONED_CONF
    assert remote.ran("systemctl restart")


def test_apply_fails_clearly_without_clamd_conf(ctx: Context, remote: FakeRemote) -> None:
    _installed(remote)
    remote.ok("systemctl daemon-reload")
    remote.ok("systemctl enable")
    with pytest.raises(StepError, match="clamd.conf is missing"):
        ClamAvStep().apply(ctx)


def test_apply_wraps_remote_errors(ctx: Context, remote: FakeRemote) -> None:
    _provisioned(remote)
    remote.files[DROP_IN_PATH] = "[Socket]\nListenStream=0.0.0.0:3310\n"
    remote.ok("systemctl daemon-reload")
    remote.fail("systemctl enable", "Failed to enable unit: Unit file clamav-daemon.socket does not exist.")
    with pytest.raises(StepError, match="ClamAV setup failed"):
        ClamAvStep().apply(ctx)


# --- verify ---------------------------------------------------------------------------------------------


def test_verify_ok_when_port_listens(ctx: Context, remote: FakeRemote) -> None:
    remote.ok("ss -ltn")
    remote.ok("systemctl is-active --quiet clamav-freshclam")
    result = _fast(ClamAvStep()).verify(ctx)
    assert result.ok
    assert result.detail == "clamd listening on 127.0.0.1:3310"
    assert remote.ran("</dev/tcp/127.0.0.1/3310")


def test_verify_warns_when_freshclam_is_down(ctx: Context, remote: FakeRemote) -> None:
    remote.ok("ss -ltn")
    result = _fast(ClamAvStep()).verify(ctx)
    assert result.ok
    assert "WARN clamav-freshclam is not active" in result.detail


def test_verify_warns_but_passes_when_socket_active_and_still_loading(ctx: Context, remote: FakeRemote) -> None:
    remote.ok("systemctl is-active --quiet clamav-daemon.socket")
    remote.ok("systemctl is-active --quiet clamav-freshclam")
    result = _fast(ClamAvStep()).verify(ctx)
    assert result.ok
    assert result.detail.startswith("WARN clamd is not accepting connections on 127.0.0.1:3310")
    assert "clamav-daemon.socket is active" in result.detail


def test_verify_fails_when_socket_inactive(ctx: Context, remote: FakeRemote) -> None:
    remote.ok("systemctl --no-pager --lines=10 status", "x clamav-daemon.socket - Socket for Clam AntiVirus\n     Active: failed (Result: exit-code)\n")
    result = _fast(ClamAvStep()).verify(ctx)
    assert not result.ok
    assert "clamav-daemon.socket is not active" in result.detail
    assert "Active: failed" in result.detail


def test_verify_polls_until_deadline(ctx: Context, remote: FakeRemote) -> None:
    answers = iter([1, 1, 0])
    remote.on("ss -ltn", lambda cmd, inp: next(answers))
    remote.ok("systemctl is-active --quiet clamav-freshclam")
    step = ClamAvStep()
    step.poll_timeout = 5.0
    step.poll_interval = 0.0
    result = step.verify(ctx)
    assert result.ok
    assert remote.count("ss -ltn") == 3


# --- describe -------------------------------------------------------------------------------------------


def test_describe_mirrors_apply(plan: InstallPlan) -> None:
    text = ClamAvStep().describe(plan)
    assert "clamav-daemon + clamav-freshclam" in text
    assert "127.0.0.1:3310" in text
    assert DROP_IN_PATH in text
    assert "StreamMaxLength 128M / MaxFileSize 128M / MaxScanSize 300M" in text
    assert CLAMD_CONF in text
